export const GET_MOVIE_ORIGINALS = 'GET_MOVIE_ORIGINALS';
export const GET_ACTION_MOVIES = 'GET_ACTION_MOVIES';
export const GET_HORROR_MOVIES = 'GET_HORROR_MOVIES';
export const GET_ROMANTIC_MOVIES = 'GET_ROMANTIC_MOVIES';
export const GET_ANIME_MOVIES = 'GET_ANIME_MOVIES';
export const GET_FICTION_MOVIES = 'GET_FICTION_MOVIES';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_DRAMA_MOVIES = 'GET_DRAMA_MOVIES';
export const GET_TV_SHOWS = 'GET_TV_SHOWS';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';

export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';
