export const GET_MOVIE_ORIGINALS = 'GET_MOVIE_ORIGINALS';
export const GET_ACTION_MOVIES = 'GET_ACTION_MOVIES';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_TV_SHOWS = 'GET_TV_SHOWS';
